default: &default
  app_name: "Resume Screening System"
  log_level: "INFO"
  openai:
    model: "gpt-4"
    embedding_model: "text-embedding-ada-002"
    api_base: "https://api.openai.com/v1"
  azure:
    region: "eastus"
    vector_db:
      type: "cosmos"
      endpoint: "https://your-default-cosmos.documents.azure.com:443/"
      index_name: "resumes"
  paths:
    resume_upload_dir: "uploads/"
    logs_dir: "logs/"
  use_mock_data: false

dev:
  <<: *default
  log_level: "DEBUG"
  openai:
    api_key_env: "DEV_OPENAI_API_KEY"
  azure:
    resource_group: "resume-screening-dev"
    vector_db:
      endpoint: "https://dev-cosmos.documents.azure.com:443/"
  use_mock_data: true

test:
  <<: *default
  log_level: "WARNING"
  openai:
    api_key_env: "TEST_OPENAI_API_KEY"
  azure:
    resource_group: "resume-screening-test"
    vector_db:
      endpoint: "https://test-cosmos.documents.azure.com:443/"
  use_mock_data: true

prod:
  <<: *default
  openai:
    api_key_env: "PROD_OPENAI_API_KEY"
  azure:
    resource_group: "resume-screening-prod"
    vector_db:
      endpoint: "https://prod-cosmos.documents.azure.com:443/"
