name: Deploy Full Infrastructure

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Target environment"
        required: true
        type: choice
        options:
          - dev
          - test
          - prod

jobs:
  deploy:
    name: Deploy infrastructure to Azure
    runs-on: ubuntu-latest

    environment: ${{ inputs.environment }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set environment variables
        id: vars
        run: |
          ENV="${{ github.event.inputs.environment }}"
          echo "ENVIRONMENT=$ENV" >> $GITHUB_OUTPUT
          echo "RESOURCE_GROUP=rg-resumescreener-$ENV" >> $GITHUB_OUTPUT
          echo "PARAMS_FILE=infra/main.$ENV.bicepparam" >> $GITHUB_OUTPUT

      - name: Ensure Azure CLI is up-to-date
        run: |
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

      - name: Run Bicep What-If Deployment
        run: |
          az account set --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }}

          az deployment group what-if \
            --resource-group ${{ steps.vars.outputs.RESOURCE_GROUP }} \
            --template-file infra/main.bicep \
            --parameters @$${{ steps.vars.outputs.PARAMS_FILE }}

      # Uncomment to actually deploy
      # - name: 🔧 Deploy Infrastructure
      #   run: |
      #     az deployment group create \
      #       --resource-group ${{ steps.vars.outputs.RESOURCE_GROUP }} \
      #       --template-file infra/main.bicep \
      #       --parameters @$${{ steps.vars.outputs.PARAMS_FILE }}
