name: Deploy Infra to Azure Prod

on:
  push:
    branches:
      - main
    paths:
      - 'infra/**'
      - '.github/workflows/deploy-prod.yml'

env:
  AZURE_LOCATION: 'eastus'
  PARAM_FILE: 'infra/parameters/prod.json'

jobs:
  deploy:
    name: Deploy Bicep to Prod
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS_PROD }}

      - name: Deploy Bicep template
        uses: azure/cli@v1
        with:
          inlineScript: |
            az account set --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID_PROD }}

            az deployment sub create \
              --location ${{ env.AZURE_LOCATION }} \
              --template-file infra/main.bicep \
              --parameters @$PARAM_FILE
